'use strict';
const slider=document.getElementById('slider');
function updateComfort(){const degrees=Number(slider.value),warm=degrees>=73;document.getElementById('deg').textContent=degrees;document.getElementById('mode').textContent=warm?'HEATING':'COOLING';document.getElementById('mode').style.color=warm?'#ffad75':'#8bcaff';document.getElementById('dt').textContent=warm?'Stay warm.':'Stay cool.';document.getElementById('dt').style.color=warm?'#ffad75':'#7fcaff';document.getElementById('dp').textContent=warm?'Heating repair, installs, and replacements for your home.':'AC repair, installs, and replacements for your home.';slider.setAttribute('aria-valuetext',`${degrees} degrees, ${warm?'heating':'cooling'}`)}
slider.addEventListener('input',updateComfort);updateComfort();
const menu=document.querySelector('.menu'),mobileNav=document.getElementById('mobile-nav');
function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation');mobileNav.hidden=true}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')==='true';mobileNav.hidden=open;menu.setAttribute('aria-expanded',String(!open));menu.setAttribute('aria-label',open?'Open navigation':'Close navigation')});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu()}});
document.querySelectorAll('[data-service]').forEach(a=>a.addEventListener('click',()=>{document.getElementById('w').value=a.dataset.service}));
// The existing Google Form has name, phone and service fields, but no details field.
// Open a prefilled form so the visitor can review, submit, and see real confirmation.
document.getElementById('rf').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const service=document.getElementById('w').value;const known=['AC repair','Heating repair','System replacement','Tune-up / Maintenance','Thermostat install'];const url=new URL('https://docs.google.com/forms/d/e/1FAIpQLSfIl1X8PNLMRop7oNGndWV8L-rVb3RM5aQ_HY5ZALHE4AsHQQ/viewform');url.searchParams.set('usp','pp_url');url.searchParams.set('entry.1284161740',document.getElementById('n').value.trim());url.searchParams.set('entry.1327681561',document.getElementById('p').value.trim());if(known.includes(service)){url.searchParams.set('entry.1965580250',service)}else{url.searchParams.set('entry.1965580250','__other_option__');url.searchParams.set('entry.1965580250.other_option_response',service)}const opened=window.open(url.href,'_blank');if(opened){opened.opener=null;document.getElementById('st').textContent='Your service form is open in a new tab. Review your information and submit it there.'}else{window.location.assign(url.href)}});
document.getElementById('year').textContent=new Date().getFullYear();
